"""Updated Model for back populates

Revision ID: c14cfbe92683
Revises: c6f5c9425fb1
Create Date: 2019-01-18 19:57:23.307432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14cfbe92683'
down_revision = 'c6f5c9425fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
