"""Updating models

Revision ID: c6f5c9425fb1
Revises: cad2e5db30d9
Create Date: 2019-01-18 11:30:26.573654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f5c9425fb1'
down_revision = 'cad2e5db30d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wordpair', sa.Column('first', sa.String(), nullable=True))
    op.add_column('wordpair', sa.Column('second', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wordpair', 'second')
    op.drop_column('wordpair', 'first')
    # ### end Alembic commands ###
