"""Updating models

Revision ID: cad2e5db30d9
Revises: e00f531f4444
Create Date: 2019-01-18 11:22:50.024357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad2e5db30d9'
down_revision = 'e00f531f4444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_language_id', sa.Integer(), nullable=True),
    sa.Column('second_language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['second_language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wordpair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['llist_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wordpair')
    op.drop_table('list')
    op.drop_table('user')
    op.drop_table('language')
    # ### end Alembic commands ###
